// Auto-generated by reading-feed/generate.py
// Last updated: 2026-01-11T00:00:10.923338

export const feedItems = [
  {
    "id": "1531581576",
    "type": "link",
    "title": "Eat Real Food",
    "excerpt": "The Dietary Guidelines for Americans reset U.S. nutrition policy by restoring science, common sense, and real food as the foundation of national health.",
    "url": "https://realfood.gov/",
    "source": "Nice Websites",
    "date": "2026-01-08",
    "domain": "realfood.gov"
  },
  {
    "id": "1531342863",
    "type": "link",
    "title": "Jakub Krehel",
    "excerpt": "Product Design Lead at OpenSea",
    "url": "https://jakub.kr/",
    "source": "Portfolios",
    "date": "2026-01-08",
    "domain": "jakub.kr"
  },
  {
    "id": "1530626712",
    "type": "link",
    "title": "https://apps.apple.com/us/app/interlude-app/id6755420190",
    "excerpt": null,
    "url": "https://apps.apple.com/us/app/interlude-app/id6755420190",
    "source": "Design",
    "date": "2026-01-07",
    "domain": "apps.apple.com"
  },
  {
    "id": "1527680669",
    "type": "link",
    "title": "Human Interface Guidelines | Axiom",
    "excerpt": "Quick decision frameworks and checklists for Apple Human Interface Guidelines",
    "url": "https://charleswiltgen.github.io/Axiom/skills/ui-design/hig",
    "source": "Portfolios",
    "date": "2026-01-05",
    "domain": "charleswiltgen.github.io"
  },
  {
    "id": "1517852745",
    "type": "link",
    "title": "Analogue Agency",
    "excerpt": "The premier destination for award-winning branding and digital design solutions. partner with our seasoned experts to elevate your brand's presence and achieve lasting impact. explore our work.",
    "url": "https://analogueagency.com/case/tonyschocolonely",
    "source": "Portfolios",
    "date": "2025-12-30",
    "domain": "analogueagency.com"
  },
  {
    "id": "1517524533",
    "type": "link",
    "title": "Why Designers Can No Longer Trust the Design Process",
    "excerpt": "For years, designers have been told to trust the process.Research first. Personas. Journey maps. Problem statements. Then solutions.In this talk from Hatch C...",
    "url": "https://www.youtube.com/watch?v=4u94juYwLLM",
    "source": "Portfolios",
    "date": "2025-12-30",
    "domain": "youtube.com"
  },
  {
    "id": "1517460727",
    "type": "link",
    "title": "Amy La",
    "excerpt": null,
    "url": "https://amylalai.com/",
    "source": "Portfolios",
    "date": "2025-12-30",
    "domain": "amylalai.com"
  },
  {
    "id": "1496359504",
    "type": "link",
    "title": "Early Works",
    "excerpt": "Early Works is a product studio that specializes in building companies from the ground up. It operates under a unique model with in-house founder-led teams.",
    "url": "https://www.early.works/",
    "source": "Portfolios",
    "date": "2025-12-19",
    "domain": "early.works"
  },
  {
    "id": "1494941677",
    "type": "link",
    "title": "Legora",
    "excerpt": "Legora is the collaborative AI powering lawyers to review and research faster, draft smarter, and advise with precision. Legora adapts to your ways of working, unlocking team and machine collaboration",
    "url": "https://legora.com/?ref=siteinspire",
    "source": "Nice Websites",
    "date": "2025-12-18",
    "domain": "legora.com"
  },
  {
    "id": "1492147346",
    "type": "link",
    "title": "achu design",
    "excerpt": "achu design is a fractional design studio helping early-stage startups grow through design leadership, product strategy, and contagious creativity.",
    "url": "https://achudesign.com/",
    "source": "Portfolios",
    "date": "2025-12-16",
    "domain": "achudesign.com"
  },
  {
    "id": "1483107990",
    "type": "link",
    "title": "Shopify Editions | Winter '26",
    "excerpt": "With 100+ updates, commerce businesses can be more productive, creative, and powerful than they ever imagined.",
    "url": "https://www.shopify.com/editions/winter2026",
    "source": "Nice Websites",
    "date": "2025-12-10",
    "domain": "shopify.com"
  },
  {
    "id": "1481647292",
    "type": "link",
    "title": "Filipe Guth - Staff Designer at Airbnb",
    "excerpt": "Designer at Airbnb, Creator of Bleemborg.com, Prev. Design Director at Work&Co",
    "url": "https://www.fguth.com/",
    "source": "Portfolios",
    "date": "2025-12-09",
    "domain": "fguth.com"
  },
  {
    "id": "1475663916",
    "type": "link",
    "title": "Sean Missal",
    "excerpt": "San Francisco based Industrial Designer",
    "url": "https://www.seanmissal.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio",
    "source": "Portfolios",
    "date": "2025-12-05",
    "domain": "seanmissal.com"
  },
  {
    "id": "1442040881",
    "type": "link",
    "title": "AI tooling for brand design",
    "excerpt": "Here\u2019s a replay of my talk with Michael Riddering on how we are leveraging AI for our brand sprints at Primary | 10 comments on LinkedIn",
    "url": "https://www.linkedin.com/posts/nick--pattison_heres-a-replay-of-my-talk-with-michael-riddering-ugcPost-7395645916642242560-cg_E/?utm_source=share&utm_medium=member_desktop&rcm=ACoAAAgXk9UBd4kak69T5IvpT4o4McVo4KVsQkM",
    "source": "Portfolios",
    "date": "2025-11-20",
    "domain": "linkedin.com"
  },
  {
    "id": "1431062965",
    "type": "link",
    "title": "Ebfaffcecbdddbcaebce",
    "excerpt": null,
    "url": "https://webassets.linear.app/files/ornj730p/production/ebfaf308fc7ec072bd1874d97dbc7a68169ebc1e.mp4",
    "source": "Portfolios",
    "date": "2025-11-12",
    "domain": "webassets.linear.app"
  },
  {
    "id": "1402841523",
    "type": "link",
    "title": "Schema",
    "excerpt": "Postgres and MySQL databases for iOS",
    "url": "https://tryschema.com/?ref=siteinspire",
    "source": "Nice Apps",
    "date": "2025-10-20",
    "domain": "tryschema.com"
  },
  {
    "id": "1342047869",
    "type": "link",
    "title": "Nicholas Christowitz",
    "excerpt": null,
    "url": "https://nicholaschristowitz.com/projects/aware/",
    "source": "Portfolios",
    "date": "2025-09-15",
    "domain": "nicholaschristowitz.com"
  },
  {
    "id": "1341918384",
    "type": "link",
    "title": "James Ayres",
    "excerpt": null,
    "url": "https://www.jamesayres.com/",
    "source": "Portfolios",
    "date": "2025-09-15",
    "domain": "jamesayres.com"
  },
  {
    "id": "1323802393",
    "type": "link",
    "title": "Gabi Robins \u2013 Brand Designer & Developer",
    "excerpt": "Gabi is a digital designer with experience building brands and websites for ambitious companies.",
    "url": "https://www.gabirobins.com/",
    "source": "Portfolios",
    "date": "2025-09-03",
    "domain": "gabirobins.com"
  },
  {
    "id": "1206837025",
    "type": "link",
    "title": "Intercom Design",
    "excerpt": "Explore the work and philosophy of the Intercom Design team. We're building the future of customer service with AI.",
    "url": "https://intercom.design/",
    "source": "Nice Websites",
    "date": "2025-06-30",
    "domain": "intercom.design"
  },
  {
    "id": "1151466633",
    "type": "link",
    "title": "A designer\u2019s guide to engaging with AI",
    "excerpt": "Jessica Hische on informed critique, staying curious, and why community matters more than ever",
    "url": "https://carly.substack.com/p/a-designers-guide-to-engaging-with",
    "source": "Design",
    "date": "2025-06-09",
    "domain": "carly.substack.com"
  },
  {
    "id": "1150386786",
    "type": "link",
    "title": "Angel investing for designers",
    "excerpt": "Issue 248: What I learned from four awesome panelists",
    "url": "https://www.proofofconcept.pub/p/angel-investing-for-designers",
    "source": "Design",
    "date": "2025-06-09",
    "domain": "proofofconcept.pub"
  },
  {
    "id": "1141665045",
    "type": "link",
    "title": "Sublime \u2014 A second brain with a soul",
    "excerpt": "Sublime is a personal knowledge management tool designed to help you save, organize, and create with everything that inspires you. Trusted by leading thinkers a...",
    "url": "https://sublime.app/",
    "source": "Nice Apps",
    "date": "2025-06-06",
    "domain": "sublime.app"
  },
  {
    "id": "1141638950",
    "type": "link",
    "title": "Honkish",
    "excerpt": "What made Honk \u2018honkish\u2019.",
    "url": "https://benji.org/honkish?trk=feed_main-feed-card_feed-article-content",
    "source": "Nice Apps",
    "date": "2025-06-06",
    "domain": "benji.org"
  },
  {
    "id": "1141275535",
    "type": "link",
    "title": "DeskMinder \u2013 Create quick desktop reminders with just one click",
    "excerpt": "A simple yet effective app for people who get easily distracted. Create quick desktop reminders with just one click.",
    "url": "https://appps.od.ua/deskminder/?utm_source=substack&utm_medium=email",
    "source": "Nice Apps",
    "date": "2025-06-06",
    "domain": "appps.od.ua"
  }
];
